#!/bin/bash
# Script to start the node server for the Netstof chat
# author: Daniel Mois

echo "Starting the Netstof chat forever";
 date +"%A, %B %-d, %Y";
 cd /home/cyberhus/devel/opeka_netstofchat/nodejs;
 forever -a -l chat.log -e err.log -o out.log main.js;
