#!/bin/bash
# Script to stop the node server for the Netstof chat
# author: Daniel Mois

 echo "Stopping the netstof chat forever";
 date +"%A, %B %-d, %Y";

 pkill node;
 echo "The Netstof chat has stopped now.";
